### ISSUE TITLE
FEATURE REQUEST: ability to save to directory (just like plex2csv has)

### ISSUE THREAD

**Issue by kossboss** [srazer/FindMissing.bundle#5] opened 2015-01-24 03:14 UTC
FEATURE REQUEST: ability to save to directory (just like plex2csv has)
That way I dont need to use the annoying plex GUI to look at the results. and I can have a nice csv file or txt file to look at for results.

**Comment by srazer** [comment] 2015-01-26 21:12
Duplicate of #3

**Closed** 2015-01-26 21:12 UTC
Labels: duplicate
